language: python
python:
  - "3.9"

services:
  - docker
branches:
  only:
    - main

before_script: pip install docker-compose

script:
  - docker-compose run user_manage_api3 sh -c "pytest -p no:warnings --cov=."
  - docker-compose run user_manage_api sh -c "python manage.py test"

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: main


