language: python
python:
  - "3.9"

services:
  - docker
branches:
  only:
    - main

before_script: pip install docker-compose

script:
  - docker compose exec reviews_api pytest -p no:warnings --cov=.

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: main


