# Generated by Django 3.1.3 on 2022-04-20 09:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Raters's id")),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name="User's username")),
                ('nr_rated_users', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Reviews')),
                ('is_signed', models.BooleanField(default=False, verbose_name='User Signed')),
                ('is_admin', models.BooleanField(default=False, verbose_name='User Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=0, help_text='1=Poor, 2=Fair, 3=Good, 4=Very Good, 5=Excellent', verbose_name='Rating')),
                ('num_replies', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Replies')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('rated_user', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_review', to='reviews.rater', verbose_name='User being rated')),
                ('rater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.rater', verbose_name='User providing the rating')),
            ],
            options={
                'unique_together': {('rater', 'rated_user')},
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reply_content', models.TextField(verbose_name='Reply')),
                ('replied_rating', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='review_reply', to='reviews.rating', verbose_name='Review being replied')),
                ('reply_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.rater', verbose_name='User providing the reply')),
            ],
            options={
                'unique_together': {('reply_user', 'replied_rating')},
            },
        ),
    ]
